spring:
  profiles:
  application:
    name: moss-sample-2.1.x

server:
  port: 8084

eureka:
  client:
    filterOnlyUpInstances: false
    registerWithEureka: true
    serviceUrl:
      defaultZone:   http://eureka.springcloud.cn/eureka/
    reference: META-INF/reference.json # optional


management.server.port: 8088

